on: [push, pull_request]
name: Checks
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.19
      id: go

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Lint
      run: make lint

    - name: Ensure go mod tidy runs without changes
      run: |
        go mod tidy
        git diff-index HEAD
        git diff-index --quiet HEAD
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Install gramine and other dependencies
      run: |
        curl -fsSLo /usr/share/keyrings/gramine-keyring.gpg https://packages.gramineproject.io/gramine-keyring.gpg
        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ focal main' | sudo tee /etc/apt/sources.list.d/gramine.list
        sudo apt-get update
        sudo apt-get install -y gcc az-dcap-client gramine

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.19
      id: go

    - name: add intel SGX repository and packages
      uses: myci-actions/add-deb-repo@11
      with:
        repo: deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main
        repo-name: intel-sgx
        keys-asc: https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
        install: libsgx-urts libsgx-dcap-quote-verify gramine-ratls-dcap

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test
      run: make test